### ISSUE TITLE
P192 speed test in ARM A35 chip

### ISSUE THREAD

**Issue by wizardk** [xiph/LPCNet#200]
chip : 1.3GHz ARM A35
code : lpcnet_efficiency
model : P192
synthetic speech length : 3600ms
synthesis time : 6700ms

The real-time rate of this test is 1.86.
The real-time rate on A53 mentioned in the [paper](https://arxiv.org/pdf/2202.11169.pdf) is 0.92.

Why is there such a big difference?

**Comment by jmvalin** [comment]
Make sure you're compiling as 64-bit ARMv8 (ideally with -O3 or even -Ofast). Also, where you using the version cited in the paper?

**Comment by wizardk** [comment]
@jmvalin , I used -Ofast and the model file is [P192](https://media.xiph.org/lpcnet/data/lpcnet_efficiency/lpcnet_data-P192.tar.gz).

**Comment by jmvalin** [comment]
It's possible your CPU/cache/memory is just slower than the specific A53 (RPi 3B+) I was using for testing.

**Comment by wizardk** [comment]
@jmvalin Will you consider using multi-core for acceleration in the future?

**Comment by jmvalin** [comment]
Very unlikely. LPCNet would be very hard to parallelize across multiple cores because of its autoregressive sample-wise architecture (which is also what makes it fast in the first place). Even if it could be done, it would only benefit a few platforms that have slow cores that can't run in real-time, but not so slow that multi-core would still be too slow.

**Comment by wizardk** [comment]
I see. Thank you.
